<?php

/**
 * @file
 * Functions to support theming.
 */

use Drupal\paragraphs\ParagraphInterface;

/**
 * Implements hook_preprocess_paragraph().
 */
function drupaljira_theme_preprocess_paragraph(array &$variables): void {
  /** @var \Drupal\paragraphs\ParagraphInterface $paragraph */
  $paragraph = $variables['paragraph'];

  // Вычисляем класс для параграфа code на основе выбранного языка.
  if ($paragraph->bundle() === 'code' && $paragraph->hasField('field_language')) {
    $language = $paragraph->get('field_language')->value;

    if (!empty($language)) {
      $parts = explode('|', $language);
      $clean_language = explode('_', $parts[0])[0];
      $variables['language_class'] = 'language-' . strtolower($clean_language);
      $variables['clean_language'] = strtoupper($clean_language);
    } else {
      $variables['language_class'] = 'language-plaintext';
      $variables['clean_language'] = '';
    }
  }

  // Вычисляем класс для параграфа callout на основе типа.
  if ($paragraph->bundle() === 'callout' && $paragraph->hasField('field_callout_type')) {
    $callout_type = $paragraph->get('field_callout_type')->value;
    if (!empty($callout_type)) {
      $parts = explode('|', $callout_type);
      $clean_type = explode('_', $parts[0])[0];
      $variables['callout_class'] = 'callout-' . strtolower($clean_type);
    } else {
      $variables['callout_class'] = 'callout-info';
    }
  }
}
